#========================================
# Test profile settings (IT tests)
#========================================
config:
  integration:
    citizenassets:
      url: http://localhost:${wiremock.server.port}/api-citizen-assets
      token-url: http://localhost:${wiremock.server.port:}/api-gateway/token
      client-id: the-client-id
      client-secret: the-client-secret
      connectTimeout: 10
      readTimeout: 20
