#-------------------------------------------------------------------------------
# Spring
#-------------------------------------------------------------------------------
spring:
    application:
        name: api-business-rules
        
#-------------------------------------------------------------------------------
# OpenAPI/Swagger-UI
#-------------------------------------------------------------------------------
openapi:
    name: ${spring.application.name}
    title: ${spring.application.name}
    version: '@project.version@'
springdoc:
    swagger-ui:
        operationsSorter: method

#-------------------------------------------------------------------------------
# Log config
#-------------------------------------------------------------------------------
logging:
    level:
        root: INFO
        