#========================================
# Test profile settings (IT tests)
#========================================
config:
  integration:
    partyassets:
      url: http://localhost:${wiremock.server.port}/api-party-assets
      token-url: http://localhost:${wiremock.server.port}/api-gateway/token
      client-id: the-client-id
      client-secret: the-client-secret
      connectTimeout: 10
      readTimeout: 20
