openapi: 3.0.1
info:
  title: api-citizenassets
  contact: {}
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: "1.1"
servers:
- url: https://api-i-test.sundsvall.se/citizenassets
  description: Generated server url
paths:
  /assets/{partyid}/{assetid}:
    put:
      tags:
      - Assets
      operationId: updateAsset
      parameters:
      - name: partyid
        in: path
        required: true
        schema:
          type: string
      - name: assetid
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AsssetUpdateRequest'
        required: true
      responses:
        "204":
          description: No content - Successful operation
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /assets:
    get:
      tags:
      - Assets
      operationId: getAssets
      parameters:
      - name: partyId
        in: query
        description: PartyId
        required: false
        schema:
          type: string
          description: PartyId
          example: 123e4567-e89b-12d3-a456-426614174000
        example: 123e4567-e89b-12d3-a456-426614174000
      - name: assetId
        in: query
        description: Asset id
        required: false
        schema:
          type: string
          description: Asset id
          example: PRH-123456789
        example: PRH-123456789
      - name: type
        in: query
        description: Asset type
        required: false
        schema:
          type: string
          description: Asset type
          example: PERMIT
        example: PERMIT
      - name: issued
        in: query
        description: Issued date
        required: false
        schema:
          type: string
          description: Issued date
          example: 2021-01-01
        example: 2021-01-01
      - name: validTo
        in: query
        description: Valid to date
        required: false
        schema:
          type: string
          description: Valid to date
          example: 2021-12-31
        example: 2021-12-31
      - name: status
        in: query
        description: Asset status
        required: false
        schema:
          type: string
          description: Asset status
          example: ACTIVE
        example: ACTIVE
      - name: description
        in: query
        description: Asset description
        required: false
        schema:
          type: string
          description: Asset description
          example: Asset description
        example: Asset description
      responses:
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Asset'
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Asset'
    post:
      tags:
      - Assets
      operationId: createAsset
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssetCreateRequest'
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "201":
          description: Created - Successful operation
          headers:
            Location:
              description: Location of the created resource.
              style: simple
          content:
            application/json:
              schema:
                type: string
            application/problem+json:
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /api-docs:
    get:
      tags:
      - API
      summary: OpenAPI
      operationId: getApiDocs
      responses:
        "200":
          description: OK
          content:
            application/yaml:
              schema:
                type: string
      x-auth-type: None
      x-throttling-tier: Unlimited
      x-wso2-mutual-ssl: Optional
  /assets/{id}:
    delete:
      tags:
      - Assets
      operationId: deleteAsset
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No content - Successful operation
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    AsssetUpdateRequest:
      type: object
      properties:
        caseReferenceIds:
          type: array
          description: Case reference ids
          example:
          - 123e4567-e89b-12d3-a456-426614174000
          items:
            type: string
            description: Case reference ids
            example: "[\"123e4567-e89b-12d3-a456-426614174000\"]"
        validTo:
          type: string
          description: Valid to date
          format: date
          example: 2021-12-31
        status:
          type: string
          description: Asset status
          example: ACTIVE
          enum:
          - ACTIVE
          - EXPIRED
          - BLOCKED
        additionalParameters:
          type: object
          additionalProperties:
            type: string
            description: Additional parameters
            example: "{\"foo\":\"bar\"}"
          description: Additional parameters
          example:
            foo: bar
    Problem:
      type: object
      properties:
        instance:
          type: string
          format: uri
        type:
          type: string
          format: uri
        parameters:
          type: object
          additionalProperties:
            type: object
        status:
          $ref: '#/components/schemas/StatusType'
        title:
          type: string
        detail:
          type: string
    StatusType:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        reasonPhrase:
          type: string
    AssetCreateRequest:
      required:
      - partyId
      type: object
      properties:
        partyId:
          type: string
          description: PartyId
          example: 123e4567-e89b-12d3-a456-426614174000
        assetId:
          type: string
          description: Asset id
          example: PRH-123456789
        caseReferenceIds:
          type: array
          description: Case reference ids
          example:
          - 123e4567-e89b-12d3-a456-426614174000
          items:
            type: string
            description: Case reference ids
            example: "[\"123e4567-e89b-12d3-a456-426614174000\"]"
        type:
          type: string
          description: Asset type
          example: PERMIT
        issued:
          type: string
          description: Issued date
          format: date
          example: 2021-01-01
        validTo:
          type: string
          description: Valid to date
          format: date
          example: 2021-12-31
        status:
          type: string
          description: Asset status
          example: ACTIVE
          enum:
          - ACTIVE
          - EXPIRED
          - BLOCKED
        description:
          type: string
          description: Asset description
          example: Asset description
        additionalParameters:
          type: object
          additionalProperties:
            type: string
            description: Additional parameters
            example: "{\"foo\":\"bar\"}"
          description: Additional parameters
          example:
            foo: bar
    Asset:
      type: object
      properties:
        assetId:
          type: string
          description: Asset id
          example: PRH-123456789
        partyId:
          type: string
          description: PartyId
          example: 123e4567-e89b-12d3-a456-426614174000
        caseReferenceIds:
          type: array
          description: Case reference ids
          example:
          - 123e4567-e89b-12d3-a456-426614174000
          items:
            type: string
            description: Case reference ids
            example: "[\"123e4567-e89b-12d3-a456-426614174000\"]"
        type:
          type: string
          description: Asset type
          example: PERMIT
        issued:
          type: string
          description: Issued date
          format: date
          example: 2021-01-01
        validTo:
          type: string
          description: Valid to date
          format: date
          example: 2021-12-31
        status:
          type: string
          description: Asset status
          example: ACTIVE
          enum:
          - ACTIVE
          - EXPIRED
          - BLOCKED
        description:
          type: string
          description: Asset description
          example: Asset description
        additionalParameters:
          type: object
          additionalProperties:
            type: string
            description: Additional parameters
            example: "{\"foo\":\"bar\"}"
          description: Additional parameters
          example:
            foo: bar
  securitySchemes: {}